// Generated by scripts/build_rides_data.py — do not edit by hand.
// Generated 2026-04-27 from analysis/data/payer_enriched_disputes.parquet.

window.RIDES = [
  {
    "id": "aetna-74177-tx-2025-q2",
    "cpt": "74177",
    "cptName": "CT scan of abdomen and pelvis with contrast",
    "awarded": 1109,
    "innRate": 133,
    "innRateP25": 83,
    "innRateP75": 185,
    "innRateN": 35,
    "innRateAsOf": null,
    "rideCost": 25.28,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 11.5,
    "pickup": {
      "label": "Excellence Emergency Hospital Llc",
      "city": "TX",
      "npi": "1972258580"
    },
    "dropoff": {
      "label": "Nearby emergency room and laboratory observations",
      "city": "TX",
      "npi": "1407990088"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of abdomen and pelvis with contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "TX",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 136,
    "punchline": "A $1,109 emergency room and laboratory observations",
    "subline": "An UberX 11.5 mi away costs about $25.28.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 74177 in TX; INN rate is the median of 35 contracted MRF rates within 11.5mi of the disputed provider.",
    "sampleDisputes": 39
  },
  {
    "id": "aetna-71275-tx-2025-q2",
    "cpt": "71275",
    "cptName": "CT scan of blood vessels of chest with contrast",
    "awarded": 1082,
    "innRate": 154,
    "innRateP25": 83,
    "innRateP75": 185,
    "innRateN": 28,
    "innRateAsOf": null,
    "rideCost": 25.28,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 11.5,
    "pickup": {
      "label": "Excellence Emergency Hospital Llc",
      "city": "TX",
      "npi": "1972258580"
    },
    "dropoff": {
      "label": "Nearby emergency room services",
      "city": "TX",
      "npi": "1407990088"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of blood vessels of chest with contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "TX",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 123,
    "punchline": "A $1,082 emergency room services",
    "subline": "An UberX 11.5 mi away costs about $25.28.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 71275 in TX; INN rate is the median of 28 contracted MRF rates within 11.5mi of the disputed provider.",
    "sampleDisputes": 13
  },
  {
    "id": "aetna-74176-tx-2025-q2",
    "cpt": "74176",
    "cptName": "CT scan of abdomen and pelvis without contrast",
    "awarded": 1051,
    "innRate": 170,
    "innRateP25": 82,
    "innRateP75": 177,
    "innRateN": 22,
    "innRateAsOf": null,
    "rideCost": 25.28,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 11.5,
    "pickup": {
      "label": "Excellence Emergency Hospital Llc",
      "city": "TX",
      "npi": "1972258580"
    },
    "dropoff": {
      "label": "Nearby emergency room services",
      "city": "TX",
      "npi": "1407990088"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of abdomen and pelvis without contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "TX",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 122,
    "punchline": "A $1,051 emergency room services",
    "subline": "An UberX 11.5 mi away costs about $25.28.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 74176 in TX; INN rate is the median of 22 contracted MRF rates within 11.5mi of the disputed provider.",
    "sampleDisputes": 7
  },
  {
    "id": "aetna-74178-tx-2025-q2",
    "cpt": "74178",
    "cptName": "CT scan of abdomen and pelvis before and after contrast",
    "awarded": 1060,
    "innRate": 201,
    "innRateP25": 94,
    "innRateP75": 350,
    "innRateN": 18,
    "innRateAsOf": null,
    "rideCost": 25.28,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 11.5,
    "pickup": {
      "label": "Excellence Emergency Hospital Llc",
      "city": "TX",
      "npi": "1972258580"
    },
    "dropoff": {
      "label": "Nearby emergency room services",
      "city": "TX",
      "npi": "1407990088"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of abdomen and pelvis before and after contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "TX",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 126,
    "punchline": "A $1,060 emergency room services",
    "subline": "An UberX 11.5 mi away costs about $25.28.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 74178 in TX; INN rate is the median of 18 contracted MRF rates within 11.5mi of the disputed provider.",
    "sampleDisputes": 2
  },
  {
    "id": "aetna-72197-az-2025-q2",
    "cpt": "72197",
    "cptName": "MRI scan of pelvis before and after contrast",
    "awarded": 1186,
    "innRate": 357,
    "innRateP25": 139,
    "innRateP75": 522,
    "innRateN": 69,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "MRI scan of pelvis before and after contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 171,
    "punchline": "A $1,186 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 72197 in AZ; INN rate is the median of 69 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 2
  },
  {
    "id": "aetna-74183-az-2025-q2",
    "cpt": "74183",
    "cptName": "MRI scan of abdomen before and after contrast",
    "awarded": 1186,
    "innRate": 359,
    "innRateP25": 139,
    "innRateP75": 498,
    "innRateN": 62,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "MRI scan of abdomen before and after contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 157,
    "punchline": "A $1,186 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 74183 in AZ; INN rate is the median of 62 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 15
  },
  {
    "id": "aetna-74177-tx-2025-q1",
    "cpt": "74177",
    "cptName": "CT scan of abdomen and pelvis with contrast",
    "awarded": 956,
    "innRate": 133,
    "innRateP25": 83,
    "innRateP75": 185,
    "innRateN": 35,
    "innRateAsOf": null,
    "rideCost": 25.28,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 11.5,
    "pickup": {
      "label": "Excellence Emergency Hospital Llc",
      "city": "TX",
      "npi": "1972258580"
    },
    "dropoff": {
      "label": "Nearby emergency room services",
      "city": "TX",
      "npi": "1407990088"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of abdomen and pelvis with contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "TX",
    "quarter": "2025-Q1",
    "outcome": "provider",
    "qpa": 117,
    "punchline": "A $956 emergency room services",
    "subline": "An UberX 11.5 mi away costs about $25.28.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 74177 in TX; INN rate is the median of 35 contracted MRF rates within 11.5mi of the disputed provider.",
    "sampleDisputes": 39
  },
  {
    "id": "aetna-74178-tx-2025-q1",
    "cpt": "74178",
    "cptName": "CT scan of abdomen and pelvis before and after contrast",
    "awarded": 1009,
    "innRate": 201,
    "innRateP25": 94,
    "innRateP75": 350,
    "innRateN": 18,
    "innRateAsOf": null,
    "rideCost": 25.28,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 11.5,
    "pickup": {
      "label": "Excellence Emergency Hospital Llc",
      "city": "TX",
      "npi": "1972258580"
    },
    "dropoff": {
      "label": "Nearby emergency room services",
      "city": "TX",
      "npi": "1407990088"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of abdomen and pelvis before and after contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "TX",
    "quarter": "2025-Q1",
    "outcome": "provider",
    "qpa": 122,
    "punchline": "A $1,009 emergency room services",
    "subline": "An UberX 11.5 mi away costs about $25.28.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 74178 in TX; INN rate is the median of 18 contracted MRF rates within 11.5mi of the disputed provider.",
    "sampleDisputes": 2
  },
  {
    "id": "aetna-74174-az-2025-q2",
    "cpt": "74174",
    "cptName": "CT scan of blood vessels of abdomen and pelvis with contrast",
    "awarded": 1171,
    "innRate": 381,
    "innRateP25": 204,
    "innRateP75": 562,
    "innRateN": 66,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of blood vessels of abdomen and pelvis with contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 159,
    "punchline": "A $1,171 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 74174 in AZ; INN rate is the median of 66 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 43
  },
  {
    "id": "aetna-71275-tx-2025-q1",
    "cpt": "71275",
    "cptName": "CT scan of blood vessels of chest with contrast",
    "awarded": 941,
    "innRate": 154,
    "innRateP25": 83,
    "innRateP75": 185,
    "innRateN": 28,
    "innRateAsOf": null,
    "rideCost": 25.28,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 11.5,
    "pickup": {
      "label": "Excellence Emergency Hospital Llc",
      "city": "TX",
      "npi": "1972258580"
    },
    "dropoff": {
      "label": "Nearby emergency room services",
      "city": "TX",
      "npi": "1407990088"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of blood vessels of chest with contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "TX",
    "quarter": "2025-Q1",
    "outcome": "provider",
    "qpa": 123,
    "punchline": "A $941 emergency room services",
    "subline": "An UberX 11.5 mi away costs about $25.28.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 71275 in TX; INN rate is the median of 28 contracted MRF rates within 11.5mi of the disputed provider.",
    "sampleDisputes": 13
  },
  {
    "id": "aetna-70498-tx-2025-q2",
    "cpt": "70498",
    "cptName": "CT scan of blood vessels of neck with contrast",
    "awarded": 922,
    "innRate": 171,
    "innRateP25": 78,
    "innRateP75": 178,
    "innRateN": 32,
    "innRateAsOf": null,
    "rideCost": 25.28,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 11.5,
    "pickup": {
      "label": "Excellence Emergency Hospital Llc",
      "city": "TX",
      "npi": "1972258580"
    },
    "dropoff": {
      "label": "Nearby emergency room services",
      "city": "TX",
      "npi": "1407990088"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of blood vessels of neck with contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "TX",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 112,
    "punchline": "A $922 emergency room services",
    "subline": "An UberX 11.5 mi away costs about $25.28.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 70498 in TX; INN rate is the median of 32 contracted MRF rates within 11.5mi of the disputed provider.",
    "sampleDisputes": 1
  },
  {
    "id": "aetna-75635-az-2024-q2",
    "cpt": "75635",
    "cptName": "CT scan of abdominal aorta and both leg arteries with contrast",
    "awarded": 976,
    "innRate": 228,
    "innRateP25": 134,
    "innRateP75": 325,
    "innRateN": 56,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of abdominal aorta and both leg arteries with contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2024-Q2",
    "outcome": "provider",
    "qpa": 160,
    "punchline": "A $976 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 75635 in AZ; INN rate is the median of 56 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 3
  },
  {
    "id": "aetna-74176-tx-2025-q1",
    "cpt": "74176",
    "cptName": "CT scan of abdomen and pelvis without contrast",
    "awarded": 914,
    "innRate": 170,
    "innRateP25": 82,
    "innRateP75": 177,
    "innRateN": 22,
    "innRateAsOf": null,
    "rideCost": 25.28,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 11.5,
    "pickup": {
      "label": "Excellence Emergency Hospital Llc",
      "city": "TX",
      "npi": "1972258580"
    },
    "dropoff": {
      "label": "Nearby emergency room services",
      "city": "TX",
      "npi": "1407990088"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of abdomen and pelvis without contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "TX",
    "quarter": "2025-Q1",
    "outcome": "provider",
    "qpa": 111,
    "punchline": "A $914 emergency room services",
    "subline": "An UberX 11.5 mi away costs about $25.28.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 74176 in TX; INN rate is the median of 22 contracted MRF rates within 11.5mi of the disputed provider.",
    "sampleDisputes": 7
  },
  {
    "id": "aetna-74176-az-2025-q2",
    "cpt": "74176",
    "cptName": "CT scan of abdomen and pelvis without contrast",
    "awarded": 914,
    "innRate": 233,
    "innRateP25": 118,
    "innRateP75": 1059,
    "innRateN": 86,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of abdomen and pelvis without contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 128,
    "punchline": "A $914 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 74176 in AZ; INN rate is the median of 86 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 236
  },
  {
    "id": "aetna-74178-az-2025-q2",
    "cpt": "74178",
    "cptName": "CT scan of abdomen and pelvis before and after contrast",
    "awarded": 1009,
    "innRate": 339,
    "innRateP25": 188,
    "innRateP75": 550,
    "innRateN": 77,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of abdomen and pelvis before and after contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 148,
    "punchline": "A $1,009 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 74178 in AZ; INN rate is the median of 77 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 14
  },
  {
    "id": "aetna-71275-az-2025-q2",
    "cpt": "71275",
    "cptName": "CT scan of blood vessels of chest with contrast",
    "awarded": 941,
    "innRate": 325,
    "innRateP25": 170,
    "innRateP75": 829,
    "innRateN": 95,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of blood vessels of chest with contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 128,
    "punchline": "A $941 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 71275 in AZ; INN rate is the median of 95 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 260
  },
  {
    "id": "aetna-70553-az-2025-q2",
    "cpt": "70553",
    "cptName": "MRI scan of brain before and after contrast",
    "awarded": 946,
    "innRate": 346,
    "innRateP25": 185,
    "innRateP75": 747,
    "innRateN": 92,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "MRI scan of brain before and after contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 170,
    "punchline": "A $946 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 70553 in AZ; INN rate is the median of 92 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 59
  },
  {
    "id": "aetna-70496-tx-2025-q2",
    "cpt": "70496",
    "cptName": "CT scan of blood vessels of head with contrast",
    "awarded": 766,
    "innRate": 168,
    "innRateP25": 80,
    "innRateP75": 178,
    "innRateN": 39,
    "innRateAsOf": null,
    "rideCost": 25.28,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 11.5,
    "pickup": {
      "label": "Excellence Emergency Hospital Llc",
      "city": "TX",
      "npi": "1972258580"
    },
    "dropoff": {
      "label": "Nearby emergency room services",
      "city": "TX",
      "npi": "1407990088"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of blood vessels of head with contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "TX",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 112,
    "punchline": "A $766 emergency room services",
    "subline": "An UberX 11.5 mi away costs about $25.28.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 70496 in TX; INN rate is the median of 39 contracted MRF rates within 11.5mi of the disputed provider.",
    "sampleDisputes": 1
  },
  {
    "id": "aetna-74174-az-2024-q2",
    "cpt": "74174",
    "cptName": "CT scan of blood vessels of abdomen and pelvis with contrast",
    "awarded": 967,
    "innRate": 381,
    "innRateP25": 204,
    "innRateP75": 562,
    "innRateN": 66,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of blood vessels of abdomen and pelvis with contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2024-Q2",
    "outcome": "provider",
    "qpa": 151,
    "punchline": "A $967 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 74174 in AZ; INN rate is the median of 66 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 43
  },
  {
    "id": "aetna-74174-az-2025-q1",
    "cpt": "74174",
    "cptName": "CT scan of blood vessels of abdomen and pelvis with contrast",
    "awarded": 967,
    "innRate": 381,
    "innRateP25": 204,
    "innRateP75": 562,
    "innRateN": 66,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of blood vessels of abdomen and pelvis with contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2025-Q1",
    "outcome": "provider",
    "qpa": 156,
    "punchline": "A $967 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 74174 in AZ; INN rate is the median of 66 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 43
  },
  {
    "id": "aetna-74177-tx-2025-q1",
    "cpt": "74177",
    "cptName": "CT scan of abdomen and pelvis with contrast",
    "awarded": 956,
    "innRate": 379,
    "innRateP25": 220,
    "innRateP75": 1694,
    "innRateN": 98,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "TX",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "TX",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of abdomen and pelvis with contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "TX",
    "quarter": "2025-Q1",
    "outcome": "provider",
    "qpa": 117,
    "punchline": "A $956 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 74177 in TX; INN rate is the median of 98 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 630
  },
  {
    "id": "aetna-74177-az-2025-q2",
    "cpt": "74177",
    "cptName": "CT scan of abdomen and pelvis with contrast",
    "awarded": 956,
    "innRate": 379,
    "innRateP25": 220,
    "innRateP75": 1694,
    "innRateN": 98,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of abdomen and pelvis with contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 134,
    "punchline": "A $956 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 74177 in AZ; INN rate is the median of 98 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 630
  },
  {
    "id": "aetna-70498-az-2025-q1",
    "cpt": "70498",
    "cptName": "CT scan of blood vessels of neck with contrast",
    "awarded": 798,
    "innRate": 242,
    "innRateP25": 137,
    "innRateP75": 386,
    "innRateN": 83,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of blood vessels of neck with contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2025-Q1",
    "outcome": "provider",
    "qpa": 117,
    "punchline": "A $798 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 70498 in AZ; INN rate is the median of 83 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 116
  },
  {
    "id": "aetna-70498-az-2025-q2",
    "cpt": "70498",
    "cptName": "CT scan of blood vessels of neck with contrast",
    "awarded": 798,
    "innRate": 242,
    "innRateP25": 137,
    "innRateP75": 386,
    "innRateN": 83,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of blood vessels of neck with contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 117,
    "punchline": "A $798 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 70498 in AZ; INN rate is the median of 83 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 116
  },
  {
    "id": "aetna-70551-tx-2025-q2",
    "cpt": "70551",
    "cptName": "MRI scan of brain without contrast",
    "awarded": 678,
    "innRate": 146,
    "innRateP25": 70,
    "innRateP75": 155,
    "innRateN": 29,
    "innRateAsOf": null,
    "rideCost": 25.28,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 11.5,
    "pickup": {
      "label": "Excellence Emergency Hospital Llc",
      "city": "TX",
      "npi": "1972258580"
    },
    "dropoff": {
      "label": "Nearby n/r",
      "city": "TX",
      "npi": "1407990088"
    },
    "patient": {
      "age": null,
      "condition": "MRI scan of brain without contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "TX",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 167,
    "punchline": "A $678 n/r",
    "subline": "An UberX 11.5 mi away costs about $25.28.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 70551 in TX; INN rate is the median of 29 contracted MRF rates within 11.5mi of the disputed provider.",
    "sampleDisputes": 1
  },
  {
    "id": "aetna-71275-az-2025-q1",
    "cpt": "71275",
    "cptName": "CT scan of blood vessels of chest with contrast",
    "awarded": 855,
    "innRate": 325,
    "innRateP25": 170,
    "innRateP75": 829,
    "innRateN": 95,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of blood vessels of chest with contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2025-Q1",
    "outcome": "provider",
    "qpa": 128,
    "punchline": "A $855 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 71275 in AZ; INN rate is the median of 95 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 260
  },
  {
    "id": "aetna-74176-az-2024-q2",
    "cpt": "74176",
    "cptName": "CT scan of abdomen and pelvis without contrast",
    "awarded": 755,
    "innRate": 233,
    "innRateP25": 118,
    "innRateP75": 1059,
    "innRateN": 86,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of abdomen and pelvis without contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2024-Q2",
    "outcome": "provider",
    "qpa": 121,
    "punchline": "A $755 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 74176 in AZ; INN rate is the median of 86 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 236
  },
  {
    "id": "aetna-74176-az-2025-q1",
    "cpt": "74176",
    "cptName": "CT scan of abdomen and pelvis without contrast",
    "awarded": 755,
    "innRate": 233,
    "innRateP25": 118,
    "innRateP75": 1059,
    "innRateN": 86,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of abdomen and pelvis without contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2025-Q1",
    "outcome": "provider",
    "qpa": 124,
    "punchline": "A $755 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 74176 in AZ; INN rate is the median of 86 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 236
  },
  {
    "id": "aetna-70487-tx-2025-q2",
    "cpt": "70487",
    "cptName": "CT scan of face with contrast",
    "awarded": 614,
    "innRate": 111,
    "innRateP25": 108,
    "innRateP75": 168,
    "innRateN": 15,
    "innRateAsOf": null,
    "rideCost": 25.28,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 11.5,
    "pickup": {
      "label": "Excellence Emergency Hospital Llc",
      "city": "TX",
      "npi": "1972258580"
    },
    "dropoff": {
      "label": "Nearby emergency room services",
      "city": "TX",
      "npi": "1407990088"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of face with contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "TX",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 93,
    "punchline": "A $614 emergency room services",
    "subline": "An UberX 11.5 mi away costs about $25.28.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 70487 in TX; INN rate is the median of 15 contracted MRF rates within 11.5mi of the disputed provider.",
    "sampleDisputes": 4
  },
  {
    "id": "aetna-71275-az-2024-q2",
    "cpt": "71275",
    "cptName": "CT scan of blood vessels of chest with contrast",
    "awarded": 816,
    "innRate": 325,
    "innRateP25": 170,
    "innRateP75": 829,
    "innRateN": 95,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of blood vessels of chest with contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2024-Q2",
    "outcome": "provider",
    "qpa": 126,
    "punchline": "A $816 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 71275 in AZ; INN rate is the median of 95 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 260
  },
  {
    "id": "aetna-73718-tx-2025-q2",
    "cpt": "73718",
    "cptName": "MRI scan of leg without contrast",
    "awarded": 630,
    "innRate": 140,
    "innRateP25": 129,
    "innRateP75": 347,
    "innRateN": 18,
    "innRateAsOf": null,
    "rideCost": 25.28,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 11.5,
    "pickup": {
      "label": "Excellence Emergency Hospital Llc",
      "city": "TX",
      "npi": "1972258580"
    },
    "dropoff": {
      "label": "Nearby emergency room services",
      "city": "TX",
      "npi": "1407990088"
    },
    "patient": {
      "age": null,
      "condition": "MRI scan of leg without contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "TX",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 130,
    "punchline": "A $630 emergency room services",
    "subline": "An UberX 11.5 mi away costs about $25.28.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 73718 in TX; INN rate is the median of 18 contracted MRF rates within 11.5mi of the disputed provider.",
    "sampleDisputes": 1
  },
  {
    "id": "aetna-75635-az-2025-q1",
    "cpt": "75635",
    "cptName": "CT scan of abdominal aorta and both leg arteries with contrast",
    "awarded": 716,
    "innRate": 228,
    "innRateP25": 134,
    "innRateP75": 325,
    "innRateN": 56,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of abdominal aorta and both leg arteries with contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2025-Q1",
    "outcome": "provider",
    "qpa": 160,
    "punchline": "A $716 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 75635 in AZ; INN rate is the median of 56 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 3
  },
  {
    "id": "aetna-77012-az-2025-q2",
    "cpt": "77012",
    "cptName": "Review by radiologist of CT guidance for needle placement",
    "awarded": 602,
    "innRate": 119,
    "innRateP25": 77,
    "innRateP75": 170,
    "innRateN": 59,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "Review by radiologist of CT guidance for needle placement",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 81,
    "punchline": "A $602 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 77012 in AZ; INN rate is the median of 59 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 8
  },
  {
    "id": "aetna-72148-tx-2025-q2",
    "cpt": "72148",
    "cptName": "MRI scan of lower spinal canal without contrast",
    "awarded": 616,
    "innRate": 142,
    "innRateP25": 70,
    "innRateP75": 166,
    "innRateN": 25,
    "innRateAsOf": null,
    "rideCost": 25.28,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 11.5,
    "pickup": {
      "label": "Excellence Emergency Hospital Llc",
      "city": "TX",
      "npi": "1972258580"
    },
    "dropoff": {
      "label": "Nearby emergency room services",
      "city": "TX",
      "npi": "1407990088"
    },
    "patient": {
      "age": null,
      "condition": "MRI scan of lower spinal canal without contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "TX",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 157,
    "punchline": "A $616 emergency room services",
    "subline": "An UberX 11.5 mi away costs about $25.28.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 72148 in TX; INN rate is the median of 25 contracted MRF rates within 11.5mi of the disputed provider.",
    "sampleDisputes": 1
  },
  {
    "id": "aetna-72141-tx-2025-q1",
    "cpt": "72141",
    "cptName": "MRI scan of upper spinal canal without contrast",
    "awarded": 616,
    "innRate": 147,
    "innRateP25": 140,
    "innRateP75": 264,
    "innRateN": 22,
    "innRateAsOf": null,
    "rideCost": 25.28,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 11.5,
    "pickup": {
      "label": "Excellence Emergency Hospital Llc",
      "city": "TX",
      "npi": "1972258580"
    },
    "dropoff": {
      "label": "Nearby emergency room services",
      "city": "TX",
      "npi": "1407990088"
    },
    "patient": {
      "age": null,
      "condition": "MRI scan of upper spinal canal without contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "TX",
    "quarter": "2025-Q1",
    "outcome": "provider",
    "qpa": 158,
    "punchline": "A $616 emergency room services",
    "subline": "An UberX 11.5 mi away costs about $25.28.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 72141 in TX; INN rate is the median of 22 contracted MRF rates within 11.5mi of the disputed provider.",
    "sampleDisputes": 2
  },
  {
    "id": "aetna-72141-tx-2025-q2",
    "cpt": "72141",
    "cptName": "MRI scan of upper spinal canal without contrast",
    "awarded": 616,
    "innRate": 147,
    "innRateP25": 140,
    "innRateP75": 264,
    "innRateN": 22,
    "innRateAsOf": null,
    "rideCost": 25.28,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 11.5,
    "pickup": {
      "label": "Excellence Emergency Hospital Llc",
      "city": "TX",
      "npi": "1972258580"
    },
    "dropoff": {
      "label": "Nearby emergency room services",
      "city": "TX",
      "npi": "1407990088"
    },
    "patient": {
      "age": null,
      "condition": "MRI scan of upper spinal canal without contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "TX",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 163,
    "punchline": "A $616 emergency room services",
    "subline": "An UberX 11.5 mi away costs about $25.28.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 72141 in TX; INN rate is the median of 22 contracted MRF rates within 11.5mi of the disputed provider.",
    "sampleDisputes": 2
  },
  {
    "id": "aetna-71260-tx-2025-q2",
    "cpt": "71260",
    "cptName": "CT scan of chest with contrast",
    "awarded": 530,
    "innRate": 73,
    "innRateP25": 51,
    "innRateP75": 119,
    "innRateN": 24,
    "innRateAsOf": null,
    "rideCost": 25.28,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 11.5,
    "pickup": {
      "label": "Excellence Emergency Hospital Llc",
      "city": "TX",
      "npi": "1972258580"
    },
    "dropoff": {
      "label": "Nearby emergency room services",
      "city": "TX",
      "npi": "1407990088"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of chest with contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "TX",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 80,
    "punchline": "A $530 emergency room services",
    "subline": "An UberX 11.5 mi away costs about $25.28.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 71260 in TX; INN rate is the median of 24 contracted MRF rates within 11.5mi of the disputed provider.",
    "sampleDisputes": 5
  },
  {
    "id": "aetna-73720-az-2025-q1",
    "cpt": "73720",
    "cptName": "MRI scan of leg before and after contrast",
    "awarded": 780,
    "innRate": 324,
    "innRateP25": 136,
    "innRateP75": 423,
    "innRateN": 56,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "MRI scan of leg before and after contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2025-Q1",
    "outcome": "provider",
    "qpa": 163,
    "punchline": "A $780 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 73720 in AZ; INN rate is the median of 56 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 10
  },
  {
    "id": "aetna-72125-tx-2025-q2",
    "cpt": "72125",
    "cptName": "CT scan of upper spine without contrast",
    "awarded": 550,
    "innRate": 96,
    "innRateP25": 46,
    "innRateP75": 102,
    "innRateN": 26,
    "innRateAsOf": null,
    "rideCost": 25.28,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 11.5,
    "pickup": {
      "label": "Excellence Emergency Hospital Llc",
      "city": "TX",
      "npi": "1972258580"
    },
    "dropoff": {
      "label": "Nearby n/r",
      "city": "TX",
      "npi": "1407990088"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of upper spine without contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "TX",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 73,
    "punchline": "A $550 n/r",
    "subline": "An UberX 11.5 mi away costs about $25.28.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 72125 in TX; INN rate is the median of 26 contracted MRF rates within 11.5mi of the disputed provider.",
    "sampleDisputes": 6
  },
  {
    "id": "aetna-71275-az-2024-q1",
    "cpt": "71275",
    "cptName": "CT scan of blood vessels of chest with contrast",
    "awarded": 777,
    "innRate": 325,
    "innRateP25": 170,
    "innRateP75": 829,
    "innRateN": 95,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of blood vessels of chest with contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2024-Q1",
    "outcome": "provider",
    "qpa": 113,
    "punchline": "A $777 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 71275 in AZ; INN rate is the median of 95 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 260
  },
  {
    "id": "aetna-70491-tx-2025-q2",
    "cpt": "70491",
    "cptName": "CT scan of soft tissue of neck with contrast",
    "awarded": 588,
    "innRate": 136,
    "innRateP25": 125,
    "innRateP75": 188,
    "innRateN": 19,
    "innRateAsOf": null,
    "rideCost": 25.28,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 11.5,
    "pickup": {
      "label": "Excellence Emergency Hospital Llc",
      "city": "TX",
      "npi": "1972258580"
    },
    "dropoff": {
      "label": "Nearby emergency room services",
      "city": "TX",
      "npi": "1407990088"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of soft tissue of neck with contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "TX",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 104,
    "punchline": "A $588 emergency room services",
    "subline": "An UberX 11.5 mi away costs about $25.28.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 70491 in TX; INN rate is the median of 19 contracted MRF rates within 11.5mi of the disputed provider.",
    "sampleDisputes": 1
  },
  {
    "id": "aetna-72156-az-2024-q2",
    "cpt": "72156",
    "cptName": "MRI scan of upper spinal canal before and after contrast",
    "awarded": 754,
    "innRate": 313,
    "innRateP25": 149,
    "innRateP75": 470,
    "innRateN": 75,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "MRI scan of upper spinal canal before and after contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2024-Q2",
    "outcome": "provider",
    "qpa": 185,
    "punchline": "A $754 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 72156 in AZ; INN rate is the median of 75 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 14
  },
  {
    "id": "aetna-70487-tx-2025-q1",
    "cpt": "70487",
    "cptName": "CT scan of face with contrast",
    "awarded": 549,
    "innRate": 111,
    "innRateP25": 108,
    "innRateP75": 168,
    "innRateN": 15,
    "innRateAsOf": null,
    "rideCost": 25.28,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 11.5,
    "pickup": {
      "label": "Excellence Emergency Hospital Llc",
      "city": "TX",
      "npi": "1972258580"
    },
    "dropoff": {
      "label": "Nearby emergency room services",
      "city": "TX",
      "npi": "1407990088"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of face with contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "TX",
    "quarter": "2025-Q1",
    "outcome": "provider",
    "qpa": 98,
    "punchline": "A $549 emergency room services",
    "subline": "An UberX 11.5 mi away costs about $25.28.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 70487 in TX; INN rate is the median of 15 contracted MRF rates within 11.5mi of the disputed provider.",
    "sampleDisputes": 4
  },
  {
    "id": "aetna-71260-tx-2025-q1",
    "cpt": "71260",
    "cptName": "CT scan of chest with contrast",
    "awarded": 504,
    "innRate": 73,
    "innRateP25": 51,
    "innRateP75": 119,
    "innRateN": 24,
    "innRateAsOf": null,
    "rideCost": 25.28,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 11.5,
    "pickup": {
      "label": "Excellence Emergency Hospital Llc",
      "city": "TX",
      "npi": "1972258580"
    },
    "dropoff": {
      "label": "Nearby emergency room services",
      "city": "TX",
      "npi": "1407990088"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of chest with contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "TX",
    "quarter": "2025-Q1",
    "outcome": "provider",
    "qpa": 80,
    "punchline": "A $504 emergency room services",
    "subline": "An UberX 11.5 mi away costs about $25.28.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 71260 in TX; INN rate is the median of 24 contracted MRF rates within 11.5mi of the disputed provider.",
    "sampleDisputes": 5
  },
  {
    "id": "aetna-77012-az-2024-q2",
    "cpt": "77012",
    "cptName": "Review by radiologist of CT guidance for needle placement",
    "awarded": 547,
    "innRate": 119,
    "innRateP25": 77,
    "innRateP75": 170,
    "innRateN": 59,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "Review by radiologist of CT guidance for needle placement",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2024-Q2",
    "outcome": "provider",
    "qpa": 76,
    "punchline": "A $547 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 77012 in AZ; INN rate is the median of 59 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 8
  },
  {
    "id": "aetna-72131-tx-2025-q2",
    "cpt": "72131",
    "cptName": "CT scan of lower spine without contrast",
    "awarded": 519,
    "innRate": 97,
    "innRateP25": 73,
    "innRateP75": 102,
    "innRateN": 20,
    "innRateAsOf": null,
    "rideCost": 25.28,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 11.5,
    "pickup": {
      "label": "Excellence Emergency Hospital Llc",
      "city": "TX",
      "npi": "1972258580"
    },
    "dropoff": {
      "label": "Nearby emergency room services",
      "city": "TX",
      "npi": "1407990088"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of lower spine without contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "TX",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 75,
    "punchline": "A $519 emergency room services",
    "subline": "An UberX 11.5 mi away costs about $25.28.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 72131 in TX; INN rate is the median of 20 contracted MRF rates within 11.5mi of the disputed provider.",
    "sampleDisputes": 2
  },
  {
    "id": "aetna-73720-az-2025-q2",
    "cpt": "73720",
    "cptName": "MRI scan of leg before and after contrast",
    "awarded": 743,
    "innRate": 324,
    "innRateP25": 136,
    "innRateP75": 423,
    "innRateN": 56,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "MRI scan of leg before and after contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 152,
    "punchline": "A $743 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 73720 in AZ; INN rate is the median of 56 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 10
  },
  {
    "id": "aetna-70496-az-2025-q1",
    "cpt": "70496",
    "cptName": "CT scan of blood vessels of head with contrast",
    "awarded": 664,
    "innRate": 250,
    "innRateP25": 137,
    "innRateP75": 544,
    "innRateN": 90,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of blood vessels of head with contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2025-Q1",
    "outcome": "provider",
    "qpa": 116,
    "punchline": "A $664 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 70496 in AZ; INN rate is the median of 90 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 102
  },
  {
    "id": "aetna-70496-az-2025-q2",
    "cpt": "70496",
    "cptName": "CT scan of blood vessels of head with contrast",
    "awarded": 664,
    "innRate": 250,
    "innRateP25": 137,
    "innRateP75": 544,
    "innRateN": 90,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "CT scan of blood vessels of head with contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 117,
    "punchline": "A $664 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 70496 in AZ; INN rate is the median of 90 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 102
  },
  {
    "id": "aetna-72146-az-2025-q2",
    "cpt": "72146",
    "cptName": "MRI scan of middle spinal canal without contrast",
    "awarded": 604,
    "innRate": 192,
    "innRateP25": 118,
    "innRateP75": 375,
    "innRateN": 76,
    "innRateAsOf": null,
    "rideCost": 12.51,
    "rideCostAsOf": "2026-04-27",
    "rideCostNote": "UberX-style estimate: $4.00 base + $1.85/mi",
    "miles": 4.6,
    "pickup": {
      "label": "Sonoran Radiology, LTD",
      "city": "AZ",
      "npi": "1033745708"
    },
    "dropoff": {
      "label": "Nearby radiology",
      "city": "AZ",
      "npi": "1730166539"
    },
    "patient": {
      "age": null,
      "condition": "MRI scan of middle spinal canal without contrast",
      "transport": "Car"
    },
    "insurer": "Aetna",
    "state": "AZ",
    "quarter": "2025-Q2",
    "outcome": "provider",
    "qpa": 107,
    "punchline": "A $604 radiology",
    "subline": "An UberX 4.6 mi away costs about $12.51.",
    "note": "Awarded shown is the 2025-Q2 state-median IDR prevailing offer for 72146 in AZ; INN rate is the median of 76 contracted MRF rates within 4.6mi of the disputed provider.",
    "sampleDisputes": 22
  }
];

window.STATS = {
  "totalDisputesAllQuarters": 3698639,
  "quartersInDocket": [
    "2024-Q1",
    "2024-Q2",
    "2025-Q1",
    "2025-Q2"
  ],
  "sampleSeeds": 2,
  "sampleCases": 50,
  "rideCostAsOf": "2026-04-27",
  "rideCostModel": "UberX-style estimate: $4.00 base + $1.85/mi",
  "innRateAsOf": null,
  "innRateSource": null,
  "note": "OON disputes vs nearby in-network MRF rates"
};
